### ISSUE TITLE
"PropertyDirection" Crash

### ISSUE THREAD

**Issue by TheSnowyChickens** [infiniteblock/MatterOverdrive-Community-Edition#9] opened 2022-01-25 03:27 UTC
Hello,
I updated from the original mod to your newest version (0.7.4) and then I found structures in my "Redstone rdy" test world and I get this crash now:

https://pastebin.com/Hn8fRXYT

First time it crashed, I was on my way to the structures. (after world reload no crash next to the structures, but 🔽)
The second time it crashed, I was on my way back to my test stuff.
(I have no MO stuff placed in my world, only some items in vanilla chests)

MC: 1.12.2
Forge: 2860
MO.CE: 0.7.4
Optifine: Yes
+ 225 other mods (IE / EIO / AE2 / &&&)

Ps: on curse forge I wrote a comment about Tritanium ore and JAOPCA integration.

**Comment by TheSnowyChickens** [comment] 2022-01-25 03:44
Is it maybe this ?
![grafik](https://user-images.githubusercontent.com/29357962/150907057-58abbd1f-d9c3-4c53-a941-96f00f8587d7.png)

(I swapped back the version)

**Comment by infiniteblock** [comment] 2022-01-25 06:25
not sure how u have done this i havent been able to replicate? also not sure why u have missing textures?

**Comment by TheSnowyChickens** [comment] 2022-01-25 17:31
In your version, you fixed structure spawn. In my play world I found never MO structures (created with the original version), so I could never have this crash. 

Something in the structures must create this crash.
(the missing textures blocks are maybe because I swapped back to the old version)

**Comment by infiniteblock** [comment] 2022-01-25 23:41
I have tried to reproduce and can't, others have also upgraded but not had an issue I will look at it again tonightSent from my Vodafone Smart N10On Jan 26, 2022 6:31 AM, TheSnowyChickens ***@***.***> wrote:
In your version, you fixed structure spawn. In my play world I found never MO structures (created with the original version), so I could never have this crash.
Something in the structures must create this crash.
(the missing textures blocks are maybe because I swapped back to the old version)

**Comment by TheSnowyChickens** [comment] 2022-01-26 00:54
[Test Flat-20220125-043332.zip](https://github.com/infiniteblock/MatterOverdrive-Community-Edition/files/7938200/Test.Flat-20220125-043332.zip)

This is my test world, use any tech based modpack with around ~227 mods.
In one of the 4 directions are the MO structures.

**Comment by infiniteblock** [comment] 2022-01-26 03:34
Well that save is 1.13....

**Comment by TheSnowyChickens** [comment] 2022-01-26 04:33
No, it's not.
Just forgot to write, that the test pach must contain the more IDs mod. (just enough ids (correct name in the mod list in the crash log, but I am not using the newest Version from the ID mod, because mixing problems)

**Comment by infiniteblock** [comment] 2022-01-26 05:44
Loading that save in 1.12.2 it gives u a warning it is 1.13 loading the level.dat in a nbt editor clearly states it's saved as a 1.13 world.Sent from my Vodafone Smart N10On Jan 26, 2022 5:33 PM, TheSnowyChickens ***@***.***> wrote:
No, it's not.
Just forgot to write, that the test pach must contain the more IDs mod. (just enough ids (correct name in the mod list in the crash log, but I am not using the newest Version from the ID mod, because mixing problems)

**Comment by infiniteblock** [comment] 2022-01-26 09:03
no matter what i try i cant reproduce this and because the save file you have sent is not even for 1.12.2 im closing this

**Comment by TheSnowyChickens** [comment] 2022-01-26 12:14
![grafik](https://user-images.githubusercontent.com/29357962/151160618-10dbe858-449b-4ec4-a610-2e9e9e453270.png)

It is okay, if you can't reproduce it, BUT IT IS NOT A 1.13+ WORLD!

Look at the picture, dim-6 / dim-12 is Aroma mining world, there is no Aroma mining world in any newer versions.
Same with Aether 2 and in "data" are more files from mods only in 1.12.2 ...

Maybe JustEnoughIDs change something in the file structure to emulate newer version code, but it is 1.12.2 ...

**Comment by infiniteblock** [comment] 2022-02-02 03:45
do you have a link to download your modpack?

**Comment by TheSnowyChickens** [comment] 2022-02-04 01:56
I don't have the pack in Curse, here is a link to the mods / configs / scripts:

https://drive.google.com/file/d/1b4g8G5HqWSVb6-S0Zqx2TNhM1kc2FQp4/view?usp=sharing

Just start it with Forge 2860.

**Closed** 2022-03-15 23:35 UTC

**Comment by infiniteblock** [comment] 2022-05-12 05:00
[MatterOverdrive-1.12.2-0.8.0-universal.zip](https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2/files/8675119/MatterOverdrive-1.12.2-0.8.0-universal.zip)

Could you try this if u still have the crashing world? you will need to extract the jar from the zip

**Comment by TheSnowyChickens** [comment] 2022-05-13 15:11
Yes, I try it.

**Comment by TheSnowyChickens** [comment] 2022-05-13 15:27
I can fly around without crashes and I can load new structures without crashes.

It looks like you fixed it. :D 

Good job 👍

**Comment by infiniteblock** [comment] 2022-05-14 04:24
!!!! yay
